# Auto-generated. Do not edit by hand.
NEWSPAPERS = [
  {
    "city": 'Decatur',
    "country": 'USA',
    "name": 'The Decatur Daily',
    "slug": 'al_dd',
    "state": 'Alabama',
  },
  {
    "city": 'Dothan',
    "country": 'USA',
    "name": 'Dothan Eagle',
    "slug": 'al_de',
    "state": 'Alabama',
  },
  {
    "city": 'Enterprise',
    "country": 'USA',
    "name": 'The Enterprise Ledger',
    "slug": 'al_el',
    "state": 'Alabama',
  },
  {
    "city": 'Florence',
    "country": 'USA',
    "name": 'TimesDaily',
    "slug": 'al_td',
    "state": 'Alabama',
  },
  {
    "city": 'Gadsden',
    "country": 'USA',
    "name": 'The Gadsden Times',
    "slug": 'al_gt',
    "state": 'Alabama',
  },
  {
    "city": 'Montgomery',
    "country": 'USA',
    "name": 'Montgomery Advertiser',
    "slug": 'al_ma',
    "state": 'Alabama',
  },
  {
    "city": 'Opelika',
    "country": 'USA',
    "name": 'Opelika-Auburn News',
    "slug": 'al_oan',
    "state": 'Alabama',
  },
  {
    "city": 'Tuscaloosa',
    "country": 'USA',
    "name": 'The Tuscaloosa News',
    "slug": 'al_tn',
    "state": 'Alabama',
  },
  {
    "city": 'Fairbanks',
    "country": 'USA',
    "name": 'Fairbanks Daily News-Miner',
    "slug": 'ak_fdnm',
    "state": 'Alaska',
  },
  {
    "city": 'Phoenix',
    "country": 'USA',
    "name": 'The Arizona Republic',
    "slug": 'az_ar',
    "state": 'Arizona',
  },
  {
    "city": 'Prescott',
    "country": 'USA',
    "name": 'The Daily Courier',
    "slug": 'az_dc',
    "state": 'Arizona',
  },
  {
    "city": 'Tucson',
    "country": 'USA',
    "name": 'Arizona Daily Star',
    "slug": 'az_ads',
    "state": 'Arizona',
  },
  {
    "city": 'Fort Smith',
    "country": 'USA',
    "name": 'Times Record',
    "slug": 'ar_tr',
    "state": 'Arkansas',
  },
  {
    "city": 'Hot Springs',
    "country": 'USA',
    "name": 'The Sentinel-Record',
    "slug": 'ar_sr',
    "state": 'Arkansas',
  },
  {
    "city": 'Hot Springs Village',
    "country": 'USA',
    "name": 'Hot Springs Village Voice',
    "slug": 'ar_hsvv',
    "state": 'Arkansas',
  },
  {
    "city": 'Little Rock',
    "country": 'USA',
    "name": 'Arkansas Democrat-Gazette',
    "slug": 'ar_adg',
    "state": 'Arkansas',
  },
  {
    "city": 'Russellville',
    "country": 'USA',
    "name": 'The Courier',
    "slug": 'ar_cn',
    "state": 'Arkansas',
  },
  {
    "city": 'Long Beach',
    "country": 'USA',
    "name": 'Press-Telegram',
    "slug": 'ca_pt',
    "state": 'California',
  },
  {
    "city": 'Los Angeles',
    "country": 'USA',
    "name": 'La Opinión',
    "slug": 'ca_lo',
    "state": 'California',
  },
  {
    "city": 'Los Angeles',
    "country": 'USA',
    "name": 'Daily News',
    "slug": 'ca_dn',
    "state": 'California',
  },
  {
    "city": 'Los Angeles',
    "country": 'USA',
    "name": 'Los Angeles Times',
    "slug": 'ca_lat',
    "state": 'California',
  },
  {
    "city": 'Monterey Pk',
    "country": 'USA',
    "name": 'World Journal - Los Angeles',
    "slug": 'ca_wjla',
    "state": 'California',
  },
  {
    "city": 'Ontario',
    "country": 'USA',
    "name": 'Inland Valley Daily Bulletin',
    "slug": 'ca_ivdb',
    "state": 'California',
  },
  {
    "city": 'Palm Springs',
    "country": 'USA',
    "name": 'The Desert Sun',
    "slug": 'ca_ds',
    "state": 'California',
  },
  {
    "city": 'Pasadena',
    "country": 'USA',
    "name": 'Pasadena Star-News',
    "slug": 'ca_psn',
    "state": 'California',
  },
  {
    "city": 'Redding',
    "country": 'USA',
    "name": 'Record Searchlight',
    "slug": 'ca_rs',
    "state": 'California',
  },
  {
    "city": 'Redlands',
    "country": 'USA',
    "name": 'Redlands Daily Facts',
    "slug": 'ca_rdf',
    "state": 'California',
  },
  {
    "city": 'Riverside',
    "country": 'USA',
    "name": 'The Press-Enterprise',
    "slug": 'ca_pe',
    "state": 'California',
  },
  {
    "city": 'Sacramento',
    "country": 'USA',
    "name": 'The Sacramento Bee',
    "slug": 'ca_sb',
    "state": 'California',
  },
  {
    "city": 'San Bernardino',
    "country": 'USA',
    "name": 'The Sun',
    "slug": 'ca_ts',
    "state": 'California',
  },
  {
    "city": 'San Francisco',
    "country": 'USA',
    "name": 'San Francisco Chronicle',
    "slug": 'ca_sfc',
    "state": 'California',
  },
  {
    "city": 'San Jose',
    "country": 'USA',
    "name": 'The Mercury News',
    "slug": 'ca_mn',
    "state": 'California',
  },
  {
    "city": 'San Rafael',
    "country": 'USA',
    "name": 'Marin Independent Journal',
    "slug": 'ca_mij',
    "state": 'California',
  },
  {
    "city": 'Santa Ana',
    "country": 'USA',
    "name": 'Orange County Register',
    "slug": 'ca_ocr',
    "state": 'California',
  },
  {
    "city": 'Stockton',
    "country": 'USA',
    "name": 'The Record',
    "slug": 'ca_tr',
    "state": 'California',
  },
  {
    "city": 'Torrance',
    "country": 'USA',
    "name": 'Daily Breeze',
    "slug": 'ca_db',
    "state": 'California',
  },
  {
    "city": 'Ventura',
    "country": 'USA',
    "name": 'Ventura County Star',
    "slug": 'ca_vcs',
    "state": 'California',
  },
  {
    "city": 'Victorville',
    "country": 'USA',
    "name": 'The Daily Press',
    "slug": 'ca_tdp',
    "state": 'California',
  },
  {
    "city": 'Walnut Creek',
    "country": 'USA',
    "name": 'East Bay Times',
    "slug": 'ca_ebt',
    "state": 'California',
  },
  {
    "city": 'West Covina',
    "country": 'USA',
    "name": 'San Gabriel Valley Tribune',
    "slug": 'ca_sgvt',
    "state": 'California',
  },
  {
    "city": 'Whittier',
    "country": 'USA',
    "name": 'Whittier Daily News',
    "slug": 'ca_wdn',
    "state": 'California',
  },
  {
    "city": 'Colorado Springs',
    "country": 'USA',
    "name": 'The Gazette',
    "slug": 'co_tg',
    "state": 'Colorado',
  },
  {
    "city": 'Fort Collins',
    "country": 'USA',
    "name": 'Fort Collins Coloradoan',
    "slug": 'co_fcc',
    "state": 'Colorado',
  },
  {
    "city": 'Grand Junction',
    "country": 'USA',
    "name": 'The Daily Sentinel',
    "slug": 'co_ds',
    "state": 'Colorado',
  },
  {
    "city": 'Pueblo',
    "country": 'USA',
    "name": 'Pueblo Chieftain',
    "slug": 'co_pc',
    "state": 'Colorado',
  },
  {
    "city": 'Bridgeport',
    "country": 'USA',
    "name": 'Connecticut Post',
    "slug": 'ct_cp',
    "state": 'Connecticut',
  },
  {
    "city": 'Danbury',
    "country": 'USA',
    "name": 'The News-Times',
    "slug": 'ct_nt',
    "state": 'Connecticut',
  },
  {
    "city": 'Greenwich',
    "country": 'USA',
    "name": 'Greenwich Time',
    "slug": 'ct_gt',
    "state": 'Connecticut',
  },
  {
    "city": 'Hartford',
    "country": 'USA',
    "name": 'Hartford Courant',
    "slug": 'ct_hc',
    "state": 'Connecticut',
  },
  {
    "city": 'Middletown',
    "country": 'USA',
    "name": 'The Middletown Press',
    "slug": 'ct_mp',
    "state": 'Connecticut',
  },
  {
    "city": 'New Haven',
    "country": 'USA',
    "name": 'New Haven Register',
    "slug": 'ct_nhr',
    "state": 'Connecticut',
  },
  {
    "city": 'New London',
    "country": 'USA',
    "name": 'The Day',
    "slug": 'ct_td',
    "state": 'Connecticut',
  },
  {
    "city": 'Norwalk',
    "country": 'USA',
    "name": 'The Norwalk Hour',
    "slug": 'ct_th',
    "state": 'Connecticut',
  },
  {
    "city": 'Norwich',
    "country": 'USA',
    "name": 'Norwich Bulletin',
    "slug": 'ct_nb',
    "state": 'Connecticut',
  },
  {
    "city": 'Stamford',
    "country": 'USA',
    "name": 'Stamford Advocate',
    "slug": 'ct_ta',
    "state": 'Connecticut',
  },
  {
    "city": 'Wilmington',
    "country": 'USA',
    "name": 'The News Journal',
    "slug": 'de_nj',
    "state": 'Delaware',
  },
  {
    "city": 'Washington',
    "country": 'USA',
    "name": 'Stars and Stripes',
    "slug": 'dc_ss',
    "state": 'District of Columbia',
  },
  {
    "city": 'Washington',
    "country": 'USA',
    "name": 'The Washington Times',
    "slug": 'dc_wt',
    "state": 'District of Columbia',
  },
  {
    "city": 'Washington',
    "country": 'USA',
    "name": 'The Washington Post',
    "slug": 'dc_wp',
    "state": 'District of Columbia',
  },
  {
    "city": 'Crystal River',
    "country": 'USA',
    "name": 'Citrus County Chronicle',
    "slug": 'fl_ccc',
    "state": 'Florida',
  },
  {
    "city": 'Daytona Beach',
    "country": 'USA',
    "name": 'The Daytona Beach News-Journal',
    "slug": 'fl_dbnj',
    "state": 'Florida',
  },
  {
    "city": 'Fort Myers',
    "country": 'USA',
    "name": 'The News-Press',
    "slug": 'fl_np',
    "state": 'Florida',
  },
  {
    "city": 'Fort Walton Beach',
    "country": 'USA',
    "name": 'Northwest Florida Daily News',
    "slug": 'fl_nfdn',
    "state": 'Florida',
  },
  {
    "city": 'Ft. Lauderdale',
    "country": 'USA',
    "name": 'Sun Sentinel',
    "slug": 'fl_ss',
    "state": 'Florida',
  },
  {
    "city": 'Gainesville',
    "country": 'USA',
    "name": 'The Gainesville Sun',
    "slug": 'fl_gs',
    "state": 'Florida',
  },
  {
    "city": 'Jacksonville',
    "country": 'USA',
    "name": 'The Florida Times-Union',
    "slug": 'fl_ftu',
    "state": 'Florida',
  },
  {
    "city": 'Lakeland',
    "country": 'USA',
    "name": 'The Ledger',
    "slug": 'fl_tl',
    "state": 'Florida',
  },
  {
    "city": 'Leesburg',
    "country": 'USA',
    "name": 'The Daily Commercial',
    "slug": 'fl_dc',
    "state": 'Florida',
  },
  {
    "city": 'Melbourne',
    "country": 'USA',
    "name": 'Florida Today',
    "slug": 'fl_ft',
    "state": 'Florida',
  },
  {
    "city": 'Miami',
    "country": 'USA',
    "name": 'The Miami Herald',
    "slug": 'fl_mh',
    "state": 'Florida',
  },
  {
    "city": 'Miami',
    "country": 'USA',
    "name": 'El Nuevo Herald',
    "slug": 'fl_enh',
    "state": 'Florida',
  },
  {
    "city": 'Naples',
    "country": 'USA',
    "name": 'Naples Daily News',
    "slug": 'fl_ndn',
    "state": 'Florida',
  },
  {
    "city": 'Ocala',
    "country": 'USA',
    "name": 'Ocala StarBanner',
    "slug": 'fl_sb',
    "state": 'Florida',
  },
  {
    "city": 'Orlando',
    "country": 'USA',
    "name": 'Orlando Sentinel',
    "slug": 'fl_os',
    "state": 'Florida',
  },
  {
    "city": 'Palm Beach',
    "country": 'USA',
    "name": 'Palm Beach Daily News',
    "slug": 'fl_pbdn',
    "state": 'Florida',
  },
  {
    "city": 'Panama City',
    "country": 'USA',
    "name": 'News Herald',
    "slug": 'fl_nh',
    "state": 'Florida',
  },
  {
    "city": 'Pensacola',
    "country": 'USA',
    "name": 'Pensacola News Journal',
    "slug": 'fl_pnj',
    "state": 'Florida',
  },
  {
    "city": 'Sarasota',
    "country": 'USA',
    "name": 'Sarasota Herald-Tribune',
    "slug": 'fl_sht',
    "state": 'Florida',
  },
  {
    "city": 'St. Augustine',
    "country": 'USA',
    "name": 'The St. Augustine Record',
    "slug": 'fl_sar',
    "state": 'Florida',
  },
  {
    "city": 'St. Petersburg',
    "country": 'USA',
    "name": 'Tampa Bay Times',
    "slug": 'fl_times',
    "state": 'Florida',
  },
  {
    "city": 'Tallahassee',
    "country": 'USA',
    "name": 'Tallahassee Democrat',
    "slug": 'fl_td',
    "state": 'Florida',
  },
  {
    "city": 'The Villages',
    "country": 'USA',
    "name": 'The Villages Daily Sun',
    "slug": 'fl_vds',
    "state": 'Florida',
  },
  {
    "city": 'West Palm Beach',
    "country": 'USA',
    "name": 'The Palm Beach Post',
    "slug": 'fl_pbp',
    "state": 'Florida',
  },
  {
    "city": 'Winter Haven',
    "country": 'USA',
    "name": 'News Chief',
    "slug": 'fl_nc',
    "state": 'Florida',
  },
  {
    "city": 'Athens',
    "country": 'USA',
    "name": 'Athens Banner-Herald',
    "slug": 'ga_abh',
    "state": 'Georgia',
  },
  {
    "city": 'Atlanta',
    "country": 'USA',
    "name": 'The Atlanta Journal-Constitution',
    "slug": 'ga_ajc',
    "state": 'Georgia',
  },
  {
    "city": 'Augusta',
    "country": 'USA',
    "name": 'The Augusta Chronicle',
    "slug": 'ga_ac',
    "state": 'Georgia',
  },
  {
    "city": 'Rome',
    "country": 'USA',
    "name": 'Rome News-Tribune',
    "slug": 'ga_rnt',
    "state": 'Georgia',
  },
  {
    "city": 'Savannah',
    "country": 'USA',
    "name": 'Savannah Morning News',
    "slug": 'ga_smn',
    "state": 'Georgia',
  },
  {
    "city": 'Lewiston',
    "country": 'USA',
    "name": 'The Lewiston Tribune',
    "slug": 'id_lmt',
    "state": 'Idaho',
  },
  {
    "city": 'Twin Falls',
    "country": 'USA',
    "name": 'Times-News',
    "slug": 'id_tn',
    "state": 'Idaho',
  },
  {
    "city": 'Aurora',
    "country": 'USA',
    "name": 'The Beacon-News',
    "slug": 'il_bn',
    "state": 'Illinois',
  },
  {
    "city": 'Bloomington',
    "country": 'USA',
    "name": 'The Pantagraph',
    "slug": 'il_tp',
    "state": 'Illinois',
  },
  {
    "city": 'Canton',
    "country": 'USA',
    "name": 'Daily Ledger',
    "slug": 'il_dl',
    "state": 'Illinois',
  },
  {
    "city": 'Chicago',
    "country": 'USA',
    "name": 'Chicago Tribune',
    "slug": 'il_ct',
    "state": 'Illinois',
  },
  {
    "city": 'Chicago',
    "country": 'USA',
    "name": 'Chicago Sun-Times',
    "slug": 'il_cst',
    "state": 'Illinois',
  },
  {
    "city": 'Danville',
    "country": 'USA',
    "name": 'Commercial-News',
    "slug": 'il_dcn',
    "state": 'Illinois',
  },
  {
    "city": 'Decatur',
    "country": 'USA',
    "name": 'Decatur Herald & Review',
    "slug": 'il_dhr',
    "state": 'Illinois',
  },
  {
    "city": 'Effingham',
    "country": 'USA',
    "name": 'Effingham Daily News',
    "slug": 'il_edn',
    "state": 'Illinois',
  },
  {
    "city": 'Freeport',
    "country": 'USA',
    "name": 'The Journal Standard',
    "slug": 'il_fjs',
    "state": 'Illinois',
  },
  {
    "city": 'Galesburg',
    "country": 'USA',
    "name": 'The Register-Mail',
    "slug": 'il_rm',
    "state": 'Illinois',
  },
  {
    "city": 'Kewanee',
    "country": 'USA',
    "name": 'Star Courier',
    "slug": 'il_sc',
    "state": 'Illinois',
  },
  {
    "city": 'Lincoln',
    "country": 'USA',
    "name": 'The Courier',
    "slug": 'il_lc',
    "state": 'Illinois',
  },
  {
    "city": 'Macomb',
    "country": 'USA',
    "name": 'McDonough County Voice',
    "slug": 'il_mcv',
    "state": 'Illinois',
  },
  {
    "city": 'Pekin',
    "country": 'USA',
    "name": 'Pekin Daily Times',
    "slug": 'il_pdt',
    "state": 'Illinois',
  },
  {
    "city": 'Peoria',
    "country": 'USA',
    "name": 'Journal Star',
    "slug": 'il_js',
    "state": 'Illinois',
  },
  {
    "city": 'Pontiac',
    "country": 'USA',
    "name": 'Daily Leader',
    "slug": 'il_pdl',
    "state": 'Illinois',
  },
  {
    "city": 'Rockford',
    "country": 'USA',
    "name": 'Rockford Register Star',
    "slug": 'il_rrs',
    "state": 'Illinois',
  },
  {
    "city": 'Springfield',
    "country": 'USA',
    "name": 'The State Journal Register',
    "slug": 'il_sjr',
    "state": 'Illinois',
  },
  {
    "city": 'Tinley Park',
    "country": 'USA',
    "name": 'Daily Southtown',
    "slug": 'il_ds',
    "state": 'Illinois',
  },
  {
    "city": 'Waukegan',
    "country": 'USA',
    "name": 'Lake County News-Sun',
    "slug": 'il_lcns',
    "state": 'Illinois',
  },
  {
    "city": 'Anderson',
    "country": 'USA',
    "name": 'The Herald Bulletin',
    "slug": 'in_hb',
    "state": 'Indiana',
  },
  {
    "city": 'Bedford',
    "country": 'USA',
    "name": 'Times-Mail',
    "slug": 'in_tm',
    "state": 'Indiana',
  },
  {
    "city": 'Bloomington',
    "country": 'USA',
    "name": 'The Herald-Times',
    "slug": 'in_ht',
    "state": 'Indiana',
  },
  {
    "city": 'Elkhart',
    "country": 'USA',
    "name": 'The Elkhart Truth',
    "slug": 'in_et',
    "state": 'Indiana',
  },
  {
    "city": 'Evansville',
    "country": 'USA',
    "name": 'Evansville Courier & Press',
    "slug": 'in_ecp',
    "state": 'Indiana',
  },
  {
    "city": 'Fort Wayne',
    "country": 'USA',
    "name": 'The Journal Gazette',
    "slug": 'in_jg',
    "state": 'Indiana',
  },
  {
    "city": 'Greensburg',
    "country": 'USA',
    "name": 'Greensburg Daily News',
    "slug": 'in_gdn',
    "state": 'Indiana',
  },
  {
    "city": 'Indianapolis',
    "country": 'USA',
    "name": 'The Indianapolis Star',
    "slug": 'in_is',
    "state": 'Indiana',
  },
  {
    "city": 'Kokomo',
    "country": 'USA',
    "name": 'Kokomo Tribune',
    "slug": 'in_kt',
    "state": 'Indiana',
  },
  {
    "city": 'Lafayette',
    "country": 'USA',
    "name": 'Journal & Courier',
    "slug": 'in_jc',
    "state": 'Indiana',
  },
  {
    "city": 'Logansport',
    "country": 'USA',
    "name": 'Pharos-Tribune',
    "slug": 'in_pha',
    "state": 'Indiana',
  },
  {
    "city": 'Martinsville',
    "country": 'USA',
    "name": 'The Reporter Times',
    "slug": 'in_rt',
    "state": 'Indiana',
  },
  {
    "city": 'Merrillville',
    "country": 'USA',
    "name": 'Post-Tribune',
    "slug": 'in_pt',
    "state": 'Indiana',
  },
  {
    "city": 'Michigan City',
    "country": 'USA',
    "name": 'La Porte County Herald-Dispatch',
    "slug": 'in_lchd',
    "state": 'Indiana',
  },
  {
    "city": 'Muncie',
    "country": 'USA',
    "name": 'The Star Press',
    "slug": 'in_sp',
    "state": 'Indiana',
  },
  {
    "city": 'Munster',
    "country": 'USA',
    "name": 'The Times',
    "slug": 'in_tt',
    "state": 'Indiana',
  },
  {
    "city": 'Richmond',
    "country": 'USA',
    "name": 'Palladium-Item',
    "slug": 'in_pi',
    "state": 'Indiana',
  },
  {
    "city": 'South Bend',
    "country": 'USA',
    "name": 'South Bend Tribune',
    "slug": 'in_sbt',
    "state": 'Indiana',
  },
  {
    "city": 'Terre Haute',
    "country": 'USA',
    "name": 'The Tribune-Star',
    "slug": 'in_ts',
    "state": 'Indiana',
  },
  {
    "city": 'Ames',
    "country": 'USA',
    "name": 'Ames Tribune',
    "slug": 'ia_tt',
    "state": 'Iowa',
  },
  {
    "city": 'Cedar Rapids',
    "country": 'USA',
    "name": 'The Gazette',
    "slug": 'ia_tg',
    "state": 'Iowa',
  },
  {
    "city": 'Des Moines',
    "country": 'USA',
    "name": 'The Des Moines Register',
    "slug": 'ia_dr',
    "state": 'Iowa',
  },
  {
    "city": 'Iowa City',
    "country": 'USA',
    "name": 'Iowa City Press-Citizen',
    "slug": 'ia_pc',
    "state": 'Iowa',
  },
  {
    "city": 'Sioux City',
    "country": 'USA',
    "name": 'Sioux City Journal',
    "slug": 'ia_scj',
    "state": 'Iowa',
  },
  {
    "city": 'Hutchinson',
    "country": 'USA',
    "name": 'The Hutchinson News',
    "slug": 'ks_hn',
    "state": 'Kansas',
  },
  {
    "city": 'Lawrence',
    "country": 'USA',
    "name": 'Lawrence Journal-World',
    "slug": 'ks_ljw',
    "state": 'Kansas',
  },
  {
    "city": 'Salina',
    "country": 'USA',
    "name": 'Salina Journal',
    "slug": 'ks_sj',
    "state": 'Kansas',
  },
  {
    "city": 'Topeka',
    "country": 'USA',
    "name": 'The Topeka Capital-Journal',
    "slug": 'ks_tcj',
    "state": 'Kansas',
  },
  {
    "city": 'Henderson',
    "country": 'USA',
    "name": 'The Gleaner',
    "slug": 'ky_tg',
    "state": 'Kentucky',
  },
  {
    "city": 'Louisville',
    "country": 'USA',
    "name": 'The Courier-Journal',
    "slug": 'ky_cj',
    "state": 'Kentucky',
  },
  {
    "city": 'Baton Rouge',
    "country": 'USA',
    "name": 'The Advocate',
    "slug": 'la_ta',
    "state": 'Louisiana',
  },
  {
    "city": 'Houma',
    "country": 'USA',
    "name": 'The Courier',
    "slug": 'la_tc',
    "state": 'Louisiana',
  },
  {
    "city": 'Lafayette',
    "country": 'USA',
    "name": 'The Acadiana Advocate',
    "slug": 'la_aca',
    "state": 'Louisiana',
  },
  {
    "city": 'Lafayette',
    "country": 'USA',
    "name": 'The Daily Advertiser',
    "slug": 'la_da',
    "state": 'Louisiana',
  },
  {
    "city": 'Monroe',
    "country": 'USA',
    "name": 'The News-Star',
    "slug": 'la_ns',
    "state": 'Louisiana',
  },
  {
    "city": 'New Orleans',
    "country": 'USA',
    "name": 'The Times-Picayune/The New Orleans Advocate',
    "slug": 'la_tpnoa',
    "state": 'Louisiana',
  },
  {
    "city": 'Shreveport',
    "country": 'USA',
    "name": 'The Times',
    "slug": 'la_tt',
    "state": 'Louisiana',
  },
  {
    "city": 'Thibodaux',
    "country": 'USA',
    "name": 'Daily Comet',
    "slug": 'la_dc',
    "state": 'Louisiana',
  },
  {
    "city": 'Augusta',
    "country": 'USA',
    "name": 'Kennebec Journal',
    "slug": 'me_kj',
    "state": 'Maine',
  },
  {
    "city": 'Portland',
    "country": 'USA',
    "name": 'Portland Press Herald',
    "slug": 'me_pph',
    "state": 'Maine',
  },
  {
    "city": 'Waterville',
    "country": 'USA',
    "name": 'Morning Sentinel',
    "slug": 'me_ms',
    "state": 'Maine',
  },
  {
    "city": 'Hagerstown',
    "country": 'USA',
    "name": 'The Herald-Mail',
    "slug": 'md_hm',
    "state": 'Maryland',
  },
  {
    "city": 'Salisbury',
    "country": 'USA',
    "name": 'The Daily Times',
    "slug": 'md_dt',
    "state": 'Maryland',
  },
  {
    "city": 'Beverly',
    "country": 'USA',
    "name": 'The Salem News',
    "slug": 'ma_sn',
    "state": 'Massachusetts',
  },
  {
    "city": 'Boston',
    "country": 'USA',
    "name": 'The Boston Globe',
    "slug": 'ma_bg',
    "state": 'Massachusetts',
  },
  {
    "city": 'Brockton',
    "country": 'USA',
    "name": 'The Enterprise',
    "slug": 'ma_te',
    "state": 'Massachusetts',
  },
  {
    "city": 'Fall River',
    "country": 'USA',
    "name": 'The Herald News',
    "slug": 'ma_hn',
    "state": 'Massachusetts',
  },
  {
    "city": 'Framingham',
    "country": 'USA',
    "name": 'Metro West Daily News',
    "slug": 'ma_mwdn',
    "state": 'Massachusetts',
  },
  {
    "city": 'Gardner',
    "country": 'USA',
    "name": 'The Gardner News',
    "slug": 'ma_gn',
    "state": 'Massachusetts',
  },
  {
    "city": 'Hyannis',
    "country": 'USA',
    "name": 'Cape Cod Times',
    "slug": 'ma_cct',
    "state": 'Massachusetts',
  },
  {
    "city": 'Milford',
    "country": 'USA',
    "name": 'The Milford Daily News',
    "slug": 'ma_mdn',
    "state": 'Massachusetts',
  },
  {
    "city": 'New Bedford',
    "country": 'USA',
    "name": 'The Standard-Times',
    "slug": 'ma_st',
    "state": 'Massachusetts',
  },
  {
    "city": 'North Andover',
    "country": 'USA',
    "name": 'The Eagle-Tribune',
    "slug": 'ma_et',
    "state": 'Massachusetts',
  },
  {
    "city": 'Quincy',
    "country": 'USA',
    "name": 'The Patriot Ledger',
    "slug": 'ma_pl',
    "state": 'Massachusetts',
  },
  {
    "city": 'Springfield',
    "country": 'USA',
    "name": 'The Republican',
    "slug": 'ma_tr',
    "state": 'Massachusetts',
  },
  {
    "city": 'Taunton',
    "country": 'USA',
    "name": 'The Taunton Daily Gazette',
    "slug": 'ma_tdg',
    "state": 'Massachusetts',
  },
  {
    "city": 'Worcester',
    "country": 'USA',
    "name": 'Telegram & Gazette',
    "slug": 'ma_tg',
    "state": 'Massachusetts',
  },
  {
    "city": 'Muskegon',
    "country": 'USA',
    "name": 'The Muskegon Chronicle',
    "slug": 'mi_mc',
    "state": 'Michigan',
  },
  {
    "city": 'Adrian',
    "country": 'USA',
    "name": 'The Daily Telegram',
    "slug": 'mi_adt',
    "state": 'Michigan',
  },
  {
    "city": 'Battle Creek',
    "country": 'USA',
    "name": 'Battle Creek Enquirer',
    "slug": 'mi_bce',
    "state": 'Michigan',
  },
  {
    "city": 'Cheboygan',
    "country": 'USA',
    "name": 'Cheboygan Daily Tribune',
    "slug": 'mi_cdt',
    "state": 'Michigan',
  },
  {
    "city": 'Coldwater',
    "country": 'USA',
    "name": 'The Daily Reporter',
    "slug": 'mi_dr',
    "state": 'Michigan',
  },
  {
    "city": 'Detroit',
    "country": 'USA',
    "name": 'Detroit Free Press',
    "slug": 'mi_dfp',
    "state": 'Michigan',
  },
  {
    "city": 'Detroit',
    "country": 'USA',
    "name": 'The Detroit News',
    "slug": 'mi_dn',
    "state": 'Michigan',
  },
  {
    "city": 'Grand Rapids',
    "country": 'USA',
    "name": 'The Grand Rapids Press',
    "slug": 'mi_grp',
    "state": 'Michigan',
  },
  {
    "city": 'Hillsdale',
    "country": 'USA',
    "name": 'The Hillsdale Daily News',
    "slug": 'mi_hdn',
    "state": 'Michigan',
  },
  {
    "city": 'Holland',
    "country": 'USA',
    "name": 'Holland Sentinel',
    "slug": 'mi_hs',
    "state": 'Michigan',
  },
  {
    "city": 'Howell',
    "country": 'USA',
    "name": 'Livingston Daily Press & Argus',
    "slug": 'mi_ldpa',
    "state": 'Michigan',
  },
  {
    "city": 'Jackson',
    "country": 'USA',
    "name": 'Jackson Citizen Patriot',
    "slug": 'mi_jcp',
    "state": 'Michigan',
  },
  {
    "city": 'Kalamazoo',
    "country": 'USA',
    "name": 'Kalamazoo Gazette',
    "slug": 'mi_kg',
    "state": 'Michigan',
  },
  {
    "city": 'Lansing',
    "country": 'USA',
    "name": 'Lansing State Journal',
    "slug": 'mi_lsj',
    "state": 'Michigan',
  },
  {
    "city": 'Monroe',
    "country": 'USA',
    "name": 'Monroe News',
    "slug": 'mi_men',
    "state": 'Michigan',
  },
  {
    "city": 'Petoskey',
    "country": 'USA',
    "name": 'Petoskey News-Review',
    "slug": 'mi_pnr',
    "state": 'Michigan',
  },
  {
    "city": 'Port Huron',
    "country": 'USA',
    "name": 'Times Herald',
    "slug": 'mi_th',
    "state": 'Michigan',
  },
  {
    "city": 'Saint Joseph',
    "country": 'USA',
    "name": 'The Herald-Palladium',
    "slug": 'mi_hp',
    "state": 'Michigan',
  },
  {
    "city": 'Sault Ste Marie',
    "country": 'USA',
    "name": 'The Sault News',
    "slug": 'mi_en',
    "state": 'Michigan',
  },
  {
    "city": 'Sturgis',
    "country": 'USA',
    "name": 'Sturgis Journal',
    "slug": 'mi_sj',
    "state": 'Michigan',
  },
  {
    "city": 'Minneapolis',
    "country": 'USA',
    "name": 'Star Tribune',
    "slug": 'mn_st',
    "state": 'Minnesota',
  },
  {
    "city": 'St. Cloud',
    "country": 'USA',
    "name": 'St. Cloud Times',
    "slug": 'mn_sct',
    "state": 'Minnesota',
  },
  {
    "city": 'St. Paul',
    "country": 'USA',
    "name": 'Pioneer Press',
    "slug": 'mn_pp',
    "state": 'Minnesota',
  },
  {
    "city": 'Jackson',
    "country": 'USA',
    "name": 'The Clarion-Ledger',
    "slug": 'ms_cl',
    "state": 'Mississippi',
  },
  {
    "city": 'Columbia',
    "country": 'USA',
    "name": 'Columbia Daily Tribune',
    "slug": 'mo_cdt',
    "state": 'Missouri',
  },
  {
    "city": 'Joplin',
    "country": 'USA',
    "name": 'The Joplin Globe',
    "slug": 'mo_jg',
    "state": 'Missouri',
  },
  {
    "city": 'Kansas City',
    "country": 'USA',
    "name": 'The Kansas City Star',
    "slug": 'mo_kcs',
    "state": 'Missouri',
  },
  {
    "city": 'Springfield',
    "country": 'USA',
    "name": 'News-Leader',
    "slug": 'mo_nl',
    "state": 'Missouri',
  },
  {
    "city": 'St. Louis',
    "country": 'USA',
    "name": 'St. Louis Post-Dispatch',
    "slug": 'mo_slpd',
    "state": 'Missouri',
  },
  {
    "city": 'Butte',
    "country": 'USA',
    "name": 'Montana Standard',
    "slug": 'mt_ms',
    "state": 'Montana',
  },
  {
    "city": 'Great Falls',
    "country": 'USA',
    "name": 'Great Falls Tribune',
    "slug": 'mt_gft',
    "state": 'Montana',
  },
  {
    "city": 'Hamilton',
    "country": 'USA',
    "name": 'Ravalli Republic',
    "slug": 'mt_rr',
    "state": 'Montana',
  },
  {
    "city": 'Helena',
    "country": 'USA',
    "name": 'Independent Record',
    "slug": 'mt_ir',
    "state": 'Montana',
  },
  {
    "city": 'Kalispell',
    "country": 'USA',
    "name": 'Daily Inter Lake',
    "slug": 'mt_dil',
    "state": 'Montana',
  },
  {
    "city": 'Libby',
    "country": 'USA',
    "name": 'The Western News',
    "slug": 'mt_twn',
    "state": 'Montana',
  },
  {
    "city": 'Missoula',
    "country": 'USA',
    "name": 'Missoulian',
    "slug": 'mt_mis',
    "state": 'Montana',
  },
  {
    "city": 'Beatrice',
    "country": 'USA',
    "name": 'Beatrice Daily Sun',
    "slug": 'ne_bds',
    "state": 'Nebraska',
  },
  {
    "city": 'Columbus',
    "country": 'USA',
    "name": 'Columbus Telegram',
    "slug": 'ne_ct',
    "state": 'Nebraska',
  },
  {
    "city": 'Fremont',
    "country": 'USA',
    "name": 'Fremont Tribune',
    "slug": 'ne_ft',
    "state": 'Nebraska',
  },
  {
    "city": 'Omaha',
    "country": 'USA',
    "name": 'Omaha World-Herald',
    "slug": 'ne_owh',
    "state": 'Nebraska',
  },
  {
    "city": 'Elko',
    "country": 'USA',
    "name": 'Elko Daily Free Press',
    "slug": 'nv_edfp',
    "state": 'Nevada',
  },
  {
    "city": 'Las Vegas',
    "country": 'USA',
    "name": 'Las Vegas Sun',
    "slug": 'nv_sun',
    "state": 'Nevada',
  },
  {
    "city": 'Reno',
    "country": 'USA',
    "name": 'Reno Gazette-Journal',
    "slug": 'nv_rgj',
    "state": 'Nevada',
  },
  {
    "city": 'Concord',
    "country": 'USA',
    "name": 'Concord Monitor',
    "slug": 'nh_cm',
    "state": 'New Hampshire',
  },
  {
    "city": 'Dover',
    "country": 'USA',
    "name": "Foster's Daily Democrat",
    "slug": 'nh_fdd',
    "state": 'New Hampshire',
  },
  {
    "city": 'Laconia',
    "country": 'USA',
    "name": 'The Laconia Daily Sun',
    "slug": 'nh_lds',
    "state": 'New Hampshire',
  },
  {
    "city": 'Manchester',
    "country": 'USA',
    "name": 'Union Leader',
    "slug": 'nh_ul',
    "state": 'New Hampshire',
  },
  {
    "city": 'Portsmouth',
    "country": 'USA',
    "name": 'Portsmouth Herald',
    "slug": 'nh_ph',
    "state": 'New Hampshire',
  },
  {
    "city": 'West Lebanon',
    "country": 'USA',
    "name": 'Valley News',
    "slug": 'nh_vn',
    "state": 'New Hampshire',
  },
  {
    "city": 'Bridgewater',
    "country": 'USA',
    "name": 'Courier News',
    "slug": 'nj_cn',
    "state": 'New Jersey',
  },
  {
    "city": 'Cherry Hill',
    "country": 'USA',
    "name": 'Courier-Post',
    "slug": 'nj_cp',
    "state": 'New Jersey',
  },
  {
    "city": 'East Brunswick',
    "country": 'USA',
    "name": 'Home News Tribune',
    "slug": 'nj_hnt',
    "state": 'New Jersey',
  },
  {
    "city": 'Mullica Hill',
    "country": 'USA',
    "name": 'South Jersey Times',
    "slug": 'nj_sjt',
    "state": 'New Jersey',
  },
  {
    "city": 'Neptune',
    "country": 'USA',
    "name": 'Asbury Park Press',
    "slug": 'nj_app',
    "state": 'New Jersey',
  },
  {
    "city": 'Newark',
    "country": 'USA',
    "name": 'The Star-Ledger',
    "slug": 'nj_sl',
    "state": 'New Jersey',
  },
  {
    "city": 'Newton',
    "country": 'USA',
    "name": 'New Jersey Herald',
    "slug": 'nj_njh',
    "state": 'New Jersey',
  },
  {
    "city": 'Parsippany',
    "country": 'USA',
    "name": 'Daily Record',
    "slug": 'nj_dr',
    "state": 'New Jersey',
  },
  {
    "city": 'Pleasantville',
    "country": 'USA',
    "name": 'The Press of Atlantic City',
    "slug": 'nj_pac',
    "state": 'New Jersey',
  },
  {
    "city": 'Trenton',
    "country": 'USA',
    "name": 'The Times of Trenton',
    "slug": 'nj_ttt',
    "state": 'New Jersey',
  },
  {
    "city": 'Vineland',
    "country": 'USA',
    "name": 'The Daily Journal',
    "slug": 'nj_dj',
    "state": 'New Jersey',
  },
  {
    "city": 'Willingboro',
    "country": 'USA',
    "name": 'Burlington County Times',
    "slug": 'nj_bct',
    "state": 'New Jersey',
  },
  {
    "city": 'Woodland Park',
    "country": 'USA',
    "name": 'Herald News',
    "slug": 'nj_hn',
    "state": 'New Jersey',
  },
  {
    "city": 'Deming',
    "country": 'USA',
    "name": 'The Deming Headlight',
    "slug": 'nm_dh',
    "state": 'New Mexico',
  },
  {
    "city": 'Las Cruces',
    "country": 'USA',
    "name": 'Las Cruces Sun-News',
    "slug": 'nm_lcsn',
    "state": 'New Mexico',
  },
  {
    "city": 'Santa Fe',
    "country": 'USA',
    "name": 'The Santa Fe New Mexican',
    "slug": 'nm_sfnm',
    "state": 'New Mexico',
  },
  {
    "city": 'Silver City',
    "country": 'USA',
    "name": 'The Silver City Daily Press and Independent',
    "slug": 'nm_scdpi',
    "state": 'New Mexico',
  },
  {
    "city": 'Albany',
    "country": 'USA',
    "name": 'Times Union',
    "slug": 'ny_tu',
    "state": 'New York',
  },
  {
    "city": 'Auburn',
    "country": 'USA',
    "name": 'The Citizen',
    "slug": 'ny_tc',
    "state": 'New York',
  },
  {
    "city": 'Binghamton',
    "country": 'USA',
    "name": 'Press & Sun-Bulletin',
    "slug": 'ny_psb',
    "state": 'New York',
  },
  {
    "city": 'Brooklyn',
    "country": 'USA',
    "name": 'El Diario - La Prensa',
    "slug": 'ny_edlp',
    "state": 'New York',
  },
  {
    "city": 'Buffalo',
    "country": 'USA',
    "name": 'The Buffalo News',
    "slug": 'ny_bn',
    "state": 'New York',
  },
  {
    "city": 'Canandaigua',
    "country": 'USA',
    "name": 'Daily Messenger',
    "slug": 'ny_daily',
    "state": 'New York',
  },
  {
    "city": 'Corning',
    "country": 'USA',
    "name": 'The Leader',
    "slug": 'ny_ctl',
    "state": 'New York',
  },
  {
    "city": 'Elmira',
    "country": 'USA',
    "name": 'Star-Gazette',
    "slug": 'ny_sg',
    "state": 'New York',
  },
  {
    "city": 'Glens Falls',
    "country": 'USA',
    "name": 'The Post-Star',
    "slug": 'ny_tps',
    "state": 'New York',
  },
  {
    "city": 'Herkimer',
    "country": 'USA',
    "name": 'Times Telegram',
    "slug": 'ny_htt',
    "state": 'New York',
  },
  {
    "city": 'Hornell',
    "country": 'USA',
    "name": 'Evening Tribune',
    "slug": 'ny_etts',
    "state": 'New York',
  },
  {
    "city": 'Ithaca',
    "country": 'USA',
    "name": 'Ithaca Journal',
    "slug": 'ny_ij',
    "state": 'New York',
  },
  {
    "city": 'Melville',
    "country": 'USA',
    "name": 'Newsday',
    "slug": 'ny_nd',
    "state": 'New York',
  },
  {
    "city": 'Middletown',
    "country": 'USA',
    "name": 'Times Herald-Record',
    "slug": 'ny_thr',
    "state": 'New York',
  },
  {
    "city": 'New York',
    "country": 'USA',
    "name": 'The Wall Street Journal',
    "slug": 'wsj',
    "state": 'New York',
  },
  {
    "city": 'New York',
    "country": 'USA',
    "name": 'Daily News',
    "slug": 'ny_dn',
    "state": 'New York',
  },
  {
    "city": 'New York',
    "country": 'USA',
    "name": 'The New York Times',
    "slug": 'ny_nyt',
    "state": 'New York',
  },
  {
    "city": 'New York',
    "country": 'USA',
    "name": 'The Epoch Times: Chinese New York Edition',
    "slug": 'ny_etcny',
    "state": 'New York',
  },
  {
    "city": 'Poughkeepsie',
    "country": 'USA',
    "name": 'Poughkeepsie Journal',
    "slug": 'ny_pj',
    "state": 'New York',
  },
  {
    "city": 'Rochester',
    "country": 'USA',
    "name": 'Rochester Democrat and Chronicle',
    "slug": 'ny_rdc',
    "state": 'New York',
  },
  {
    "city": 'Staten Island',
    "country": 'USA',
    "name": 'Staten Island Advance',
    "slug": 'ny_sia',
    "state": 'New York',
  },
  {
    "city": 'Syracuse',
    "country": 'USA',
    "name": 'The Post-Standard',
    "slug": 'ny_ps',
    "state": 'New York',
  },
  {
    "city": 'Utica',
    "country": 'USA',
    "name": 'Observer-Dispatch',
    "slug": 'ny_od',
    "state": 'New York',
  },
  {
    "city": 'Westchester County',
    "country": 'USA',
    "name": 'The Journal News',
    "slug": 'ny_jn',
    "state": 'New York',
  },
  {
    "city": 'Whitestone',
    "country": 'USA',
    "name": 'World Journal - New York',
    "slug": 'ny_wjny',
    "state": 'New York',
  },
  {
    "city": 'Asheville',
    "country": 'USA',
    "name": 'Asheville Citizen-Times',
    "slug": 'nc_act',
    "state": 'North Carolina',
  },
  {
    "city": 'Fayetteville',
    "country": 'USA',
    "name": 'The Fayetteville Observer',
    "slug": 'nc_fo',
    "state": 'North Carolina',
  },
  {
    "city": 'Gastonia',
    "country": 'USA',
    "name": 'Gaston Gazette',
    "slug": 'nc_gg',
    "state": 'North Carolina',
  },
  {
    "city": 'Greensboro',
    "country": 'USA',
    "name": 'News & Record',
    "slug": 'nc_nr',
    "state": 'North Carolina',
  },
  {
    "city": 'Hendersonville',
    "country": 'USA',
    "name": 'Times-News',
    "slug": 'nc_tn',
    "state": 'North Carolina',
  },
  {
    "city": 'Hickory',
    "country": 'USA',
    "name": 'Hickory Daily Record',
    "slug": 'nc_hdr',
    "state": 'North Carolina',
  },
  {
    "city": 'Kannapolis',
    "country": 'USA',
    "name": 'The Independent Tribune',
    "slug": 'nc_it',
    "state": 'North Carolina',
  },
  {
    "city": 'Marion',
    "country": 'USA',
    "name": 'The McDowell News',
    "slug": 'nc_mn',
    "state": 'North Carolina',
  },
  {
    "city": 'Mooresville',
    "country": 'USA',
    "name": 'Mooresville Tribune',
    "slug": 'nc_mt',
    "state": 'North Carolina',
  },
  {
    "city": 'Morganton',
    "country": 'USA',
    "name": 'The News Herald',
    "slug": 'nc_nh',
    "state": 'North Carolina',
  },
  {
    "city": 'Shelby',
    "country": 'USA',
    "name": 'The Star',
    "slug": 'nc_ts',
    "state": 'North Carolina',
  },
  {
    "city": 'Statesville',
    "country": 'USA',
    "name": 'Statesville Record & Landmark',
    "slug": 'nc_srl',
    "state": 'North Carolina',
  },
  {
    "city": 'Wilmington',
    "country": 'USA',
    "name": 'Star News',
    "slug": 'nc_star',
    "state": 'North Carolina',
  },
  {
    "city": 'Winston-Salem',
    "country": 'USA',
    "name": 'Winston-Salem Journal',
    "slug": 'nc_wsj',
    "state": 'North Carolina',
  },
  {
    "city": 'Akron',
    "country": 'USA',
    "name": 'Akron Beacon Journal',
    "slug": 'oh_abj',
    "state": 'Ohio',
  },
  {
    "city": 'Alliance',
    "country": 'USA',
    "name": 'The Alliance Review',
    "slug": 'oh_ar',
    "state": 'Ohio',
  },
  {
    "city": 'Ashland',
    "country": 'USA',
    "name": 'Ashland Times Gazette',
    "slug": 'oh_atg',
    "state": 'Ohio',
  },
  {
    "city": 'Bucyrus',
    "country": 'USA',
    "name": 'Telegraph-Forum',
    "slug": 'oh_tf',
    "state": 'Ohio',
  },
  {
    "city": 'Canton',
    "country": 'USA',
    "name": 'The Repository',
    "slug": 'oh_rep',
    "state": 'Ohio',
  },
  {
    "city": 'Chillicothe',
    "country": 'USA',
    "name": 'Chillicothe Gazette',
    "slug": 'oh_cg',
    "state": 'Ohio',
  },
  {
    "city": 'Cincinnati',
    "country": 'USA',
    "name": 'The Cincinnati Enquirer',
    "slug": 'oh_ce',
    "state": 'Ohio',
  },
  {
    "city": 'Cleveland',
    "country": 'USA',
    "name": 'The Plain Dealer',
    "slug": 'oh_cpd',
    "state": 'Ohio',
  },
  {
    "city": 'Columbus',
    "country": 'USA',
    "name": 'The Columbus Dispatch',
    "slug": 'oh_cd',
    "state": 'Ohio',
  },
  {
    "city": 'Coshocton',
    "country": 'USA',
    "name": 'Coshocton Tribune',
    "slug": 'oh_cot',
    "state": 'Ohio',
  },
  {
    "city": 'Dayton',
    "country": 'USA',
    "name": 'Dayton Daily News',
    "slug": 'oh_ddn',
    "state": 'Ohio',
  },
  {
    "city": 'Dover-New Philadelphia',
    "country": 'USA',
    "name": 'The Times-Reporter',
    "slug": 'oh_tr',
    "state": 'Ohio',
  },
  {
    "city": 'Fremont',
    "country": 'USA',
    "name": 'The News-Messenger',
    "slug": 'oh_nm',
    "state": 'Ohio',
  },
  {
    "city": 'Hamilton',
    "country": 'USA',
    "name": 'Journal News',
    "slug": 'oh_jn',
    "state": 'Ohio',
  },
  {
    "city": 'Lancaster',
    "country": 'USA',
    "name": 'Lancaster Eagle-Gazette',
    "slug": 'oh_leg',
    "state": 'Ohio',
  },
  {
    "city": 'Mansfield',
    "country": 'USA',
    "name": 'Mansfield News Journal',
    "slug": 'oh_mnj',
    "state": 'Ohio',
  },
  {
    "city": 'Marion',
    "country": 'USA',
    "name": 'The Marion Star',
    "slug": 'oh_ms',
    "state": 'Ohio',
  },
  {
    "city": 'Massillon',
    "country": 'USA',
    "name": 'The Independent',
    "slug": 'oh_ti',
    "state": 'Ohio',
  },
  {
    "city": 'Newark',
    "country": 'USA',
    "name": 'The Newark Advocate',
    "slug": 'oh_na',
    "state": 'Ohio',
  },
  {
    "city": 'Port Clinton',
    "country": 'USA',
    "name": 'Port Clinton News Herald',
    "slug": 'oh_pcnh',
    "state": 'Ohio',
  },
  {
    "city": 'Ravenna',
    "country": 'USA',
    "name": 'The Record-Courier',
    "slug": 'oh_rc',
    "state": 'Ohio',
  },
  {
    "city": 'Springfield',
    "country": 'USA',
    "name": 'Springfield News Sun',
    "slug": 'oh_sns',
    "state": 'Ohio',
  },
  {
    "city": 'Toledo',
    "country": 'USA',
    "name": 'The Blade',
    "slug": 'oh_tb',
    "state": 'Ohio',
  },
  {
    "city": 'Wooster',
    "country": 'USA',
    "name": 'The Daily Record',
    "slug": 'oh_dr',
    "state": 'Ohio',
  },
  {
    "city": 'Zanesville',
    "country": 'USA',
    "name": 'The Zanesville Times Recorder',
    "slug": 'oh_ztr',
    "state": 'Ohio',
  },
  {
    "city": 'Bartlesville',
    "country": 'USA',
    "name": 'Examiner-Enterprise',
    "slug": 'ok_ee',
    "state": 'Oklahoma',
  },
  {
    "city": 'Oklahoma City',
    "country": 'USA',
    "name": 'The Oklahoman',
    "slug": 'ok_dok',
    "state": 'Oklahoma',
  },
  {
    "city": 'Tulsa',
    "country": 'USA',
    "name": 'Tulsa World',
    "slug": 'ok_tw',
    "state": 'Oklahoma',
  },
  {
    "city": 'Weatherford',
    "country": 'USA',
    "name": 'Weatherford Daily News',
    "slug": 'ok_wedn',
    "state": 'Oklahoma',
  },
  {
    "city": 'Eugene',
    "country": 'USA',
    "name": 'The Register-Guard',
    "slug": 'or_rg',
    "state": 'Oregon',
  },
  {
    "city": 'Salem',
    "country": 'USA',
    "name": 'Statesman Journal',
    "slug": 'or_sj',
    "state": 'Oregon',
  },
  {
    "city": 'Allentown',
    "country": 'USA',
    "name": 'The Morning Call',
    "slug": 'pa_mc',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Altoona',
    "country": 'USA',
    "name": 'Altoona Mirror',
    "slug": 'pa_am',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Bridgewater',
    "country": 'USA',
    "name": 'Beaver County Times',
    "slug": 'pa_bct',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Chambersburg',
    "country": 'USA',
    "name": 'Chambersburg Public Opinion',
    "slug": 'pa_cpo',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Doylestown',
    "country": 'USA',
    "name": 'The Intelligencer',
    "slug": 'pa_ti',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Ellwood City',
    "country": 'USA',
    "name": 'Ellwood City Ledger',
    "slug": 'pa_ecl',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Erie',
    "country": 'USA',
    "name": 'Erie Gay News',
    "slug": 'pa_egn',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Erie',
    "country": 'USA',
    "name": 'Erie Times-News',
    "slug": 'pa_etn',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Greensburg',
    "country": 'USA',
    "name": 'Tribune-Review - Westmoreland Edition',
    "slug": 'pa_trw',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Hanover',
    "country": 'USA',
    "name": 'Hanover Evening Sun',
    "slug": 'pa_hes',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Harrisburg',
    "country": 'USA',
    "name": 'The Patriot-News',
    "slug": 'pa_pn',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Hazleton',
    "country": 'USA',
    "name": 'Standard-Speaker',
    "slug": 'pa_ss',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Honesdale',
    "country": 'USA',
    "name": 'Tri-County Independent',
    "slug": 'pa_tci',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Lebanon',
    "country": 'USA',
    "name": 'Lebanon Daily News',
    "slug": 'pa_ldn',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Levittown',
    "country": 'USA',
    "name": 'Bucks County Courier Times',
    "slug": 'pa_bcct',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Philadelphia',
    "country": 'USA',
    "name": 'The Philadelphia Inquirer',
    "slug": 'pa_pi',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Pittsburgh',
    "country": 'USA',
    "name": 'Pittsburgh Post-Gazette',
    "slug": 'pa_ppg',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Pottsville',
    "country": 'USA',
    "name": 'The Republican-Herald',
    "slug": 'pa_rh',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Scranton',
    "country": 'USA',
    "name": 'The Times-Tribune',
    "slug": 'pa_tt',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Somerset',
    "country": 'USA',
    "name": 'Daily American',
    "slug": 'pa_da',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Stroudsburg',
    "country": 'USA',
    "name": 'Pocono Record',
    "slug": 'pa_pr',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Sunbury',
    "country": 'USA',
    "name": 'The Daily Item',
    "slug": 'pa_di',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Waynesboro',
    "country": 'USA',
    "name": 'The Record Herald',
    "slug": 'pa_wrh',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Wilkes-Barre',
    "country": 'USA',
    "name": "The Citizens' Voice",
    "slug": 'pa_cv',
    "state": 'Pennsylvania',
  },
  {
    "city": 'York',
    "country": 'USA',
    "name": 'York Daily Record',
    "slug": 'pa_ydr',
    "state": 'Pennsylvania',
  },
  {
    "city": 'York',
    "country": 'USA',
    "name": 'York Dispatch',
    "slug": 'pa_yd',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Newport',
    "country": 'USA',
    "name": 'Newport Daily News',
    "slug": 'ri_ndn',
    "state": 'Rhode Island',
  },
  {
    "city": 'Providence',
    "country": 'USA',
    "name": 'The Providence Journal',
    "slug": 'ri_pj',
    "state": 'Rhode Island',
  },
  {
    "city": 'Westerly',
    "country": 'USA',
    "name": 'The Westerly Sun',
    "slug": 'ri_ws',
    "state": 'Rhode Island',
  },
  {
    "city": 'Anderson',
    "country": 'USA',
    "name": 'Anderson Independent-Mail',
    "slug": 'sc_im',
    "state": 'South Carolina',
  },
  {
    "city": 'Florence',
    "country": 'USA',
    "name": 'The Morning News',
    "slug": 'sc_mn',
    "state": 'South Carolina',
  },
  {
    "city": 'Greenville',
    "country": 'USA',
    "name": 'The Greenville News',
    "slug": 'sc_gn',
    "state": 'South Carolina',
  },
  {
    "city": 'Orangeburg',
    "country": 'USA',
    "name": 'The Times and Democrat',
    "slug": 'sc_td',
    "state": 'South Carolina',
  },
  {
    "city": 'Spartanburg',
    "country": 'USA',
    "name": 'Herald Journal',
    "slug": 'sc_hj',
    "state": 'South Carolina',
  },
  {
    "city": 'Aberdeen',
    "country": 'USA',
    "name": 'American News',
    "slug": 'sd_an',
    "state": 'South Dakota',
  },
  {
    "city": 'Rapid City',
    "country": 'USA',
    "name": 'Rapid City Journal',
    "slug": 'sd_rcj',
    "state": 'South Dakota',
  },
  {
    "city": 'Sioux Falls',
    "country": 'USA',
    "name": 'Argus Leader',
    "slug": 'sd_sfal',
    "state": 'South Dakota',
  },
  {
    "city": 'Watertown',
    "country": 'USA',
    "name": 'Watertown Public Opinion',
    "slug": 'sd_wpo',
    "state": 'South Dakota',
  },
  {
    "city": 'Yankton',
    "country": 'USA',
    "name": 'Yankton Daily Press',
    "slug": 'sd_ydp',
    "state": 'South Dakota',
  },
  {
    "city": 'Chattanooga',
    "country": 'USA',
    "name": 'Chattanooga Times Free Press',
    "slug": 'tn_ctfp',
    "state": 'Tennessee',
  },
  {
    "city": 'Clarksville',
    "country": 'USA',
    "name": 'The Leaf-Chronicle',
    "slug": 'tn_lc',
    "state": 'Tennessee',
  },
  {
    "city": 'Columbia',
    "country": 'USA',
    "name": 'The Daily Herald',
    "slug": 'tn_dh',
    "state": 'Tennessee',
  },
  {
    "city": 'Jackson',
    "country": 'USA',
    "name": 'The Jackson Sun',
    "slug": 'tn_js',
    "state": 'Tennessee',
  },
  {
    "city": 'Knoxville',
    "country": 'USA',
    "name": 'News Sentinel',
    "slug": 'tn_kns',
    "state": 'Tennessee',
  },
  {
    "city": 'Memphis',
    "country": 'USA',
    "name": 'The Commercial Appeal',
    "slug": 'tn_ca',
    "state": 'Tennessee',
  },
  {
    "city": 'Murfreesboro',
    "country": 'USA',
    "name": 'The Daily News Journal',
    "slug": 'tn_dnj',
    "state": 'Tennessee',
  },
  {
    "city": 'Nashville',
    "country": 'USA',
    "name": 'The Tennessean',
    "slug": 'tn_tt',
    "state": 'Tennessee',
  },
  {
    "city": 'Oak Ridge',
    "country": 'USA',
    "name": 'The Oak Ridger',
    "slug": 'tn_or',
    "state": 'Tennessee',
  },
  {
    "city": 'Abilene',
    "country": 'USA',
    "name": 'Abilene Reporter-News',
    "slug": 'tx_arn',
    "state": 'Texas',
  },
  {
    "city": 'Amarillo',
    "country": 'USA',
    "name": 'Amarillo Globe-News',
    "slug": 'tx_agn',
    "state": 'Texas',
  },
  {
    "city": 'Austin',
    "country": 'USA',
    "name": 'Austin American-Statesman',
    "slug": 'tx_aashn',
    "state": 'Texas',
  },
  {
    "city": 'Beaumont',
    "country": 'USA',
    "name": 'The Beaumont Enterprise',
    "slug": 'tx_be',
    "state": 'Texas',
  },
  {
    "city": 'Corpus Christi',
    "country": 'USA',
    "name": 'Corpus Christi Caller-Times',
    "slug": 'tx_ccct',
    "state": 'Texas',
  },
  {
    "city": 'Dallas',
    "country": 'USA',
    "name": 'The Dallas Morning News',
    "slug": 'tx_dmn',
    "state": 'Texas',
  },
  {
    "city": 'Denton',
    "country": 'USA',
    "name": 'Denton Record-Chronicle',
    "slug": 'tx_drc',
    "state": 'Texas',
  },
  {
    "city": 'El Paso',
    "country": 'USA',
    "name": 'El Paso Times',
    "slug": 'tx_ept',
    "state": 'Texas',
  },
  {
    "city": 'Houston',
    "country": 'USA',
    "name": 'Houston Chronicle',
    "slug": 'tx_hc',
    "state": 'Texas',
  },
  {
    "city": 'Laredo',
    "country": 'USA',
    "name": 'Laredo Morning Times',
    "slug": 'tx_lmt',
    "state": 'Texas',
  },
  {
    "city": 'Longview',
    "country": 'USA',
    "name": 'Longview News-Journal',
    "slug": 'tx_lnj',
    "state": 'Texas',
  },
  {
    "city": 'Lubbock',
    "country": 'USA',
    "name": 'Lubbock Avalanche-Journal',
    "slug": 'tx_laj',
    "state": 'Texas',
  },
  {
    "city": 'Marshall',
    "country": 'USA',
    "name": 'The Marshall News Messenger',
    "slug": 'tx_mnm',
    "state": 'Texas',
  },
  {
    "city": 'San Angelo',
    "country": 'USA',
    "name": 'Standard-Times',
    "slug": 'tx_st',
    "state": 'Texas',
  },
  {
    "city": 'San Antonio',
    "country": 'USA',
    "name": 'San Antonio Express-News',
    "slug": 'tx_saen',
    "state": 'Texas',
  },
  {
    "city": 'Temple',
    "country": 'USA',
    "name": 'Temple Daily Telegram',
    "slug": 'tx_tdt',
    "state": 'Texas',
  },
  {
    "city": 'Texarkana',
    "country": 'USA',
    "name": 'Texarkana Gazette',
    "slug": 'tx_tg',
    "state": 'Texas',
  },
  {
    "city": 'Tyler',
    "country": 'USA',
    "name": 'Tyler Morning Telegraph',
    "slug": 'tx_tmt',
    "state": 'Texas',
  },
  {
    "city": 'Victoria',
    "country": 'USA',
    "name": 'Victoria Advocate',
    "slug": 'tx_va',
    "state": 'Texas',
  },
  {
    "city": 'Waco',
    "country": 'USA',
    "name": 'Waco Tribune-Herald',
    "slug": 'tx_wth',
    "state": 'Texas',
  },
  {
    "city": 'Wichita Falls',
    "country": 'USA',
    "name": 'Times Record News',
    "slug": 'tx_trn',
    "state": 'Texas',
  },
  {
    "city": 'Provo',
    "country": 'USA',
    "name": 'The Daily Herald',
    "slug": 'ut_dh',
    "state": 'Utah',
  },
  {
    "city": 'St. George',
    "country": 'USA',
    "name": 'The Spectrum',
    "slug": 'ut_ts',
    "state": 'Utah',
  },
  {
    "city": 'Burlington',
    "country": 'USA',
    "name": 'The Burlington Free Press',
    "slug": 'vt_bfp',
    "state": 'Vermont',
  },
  {
    "city": 'Bristol',
    "country": 'USA',
    "name": 'Bristol Herald Courier',
    "slug": 'va_bhc',
    "state": 'Virginia',
  },
  {
    "city": 'Charlottesville',
    "country": 'USA',
    "name": 'Daily Progress',
    "slug": 'va_dp',
    "state": 'Virginia',
  },
  {
    "city": 'Culpeper',
    "country": 'USA',
    "name": 'Culpeper Star-Exponent',
    "slug": 'va_cse',
    "state": 'Virginia',
  },
  {
    "city": 'Danville',
    "country": 'USA',
    "name": 'Danville Register & Bee',
    "slug": 'va_drb',
    "state": 'Virginia',
  },
  {
    "city": 'Fredericksburg',
    "country": 'USA',
    "name": 'The Free Lance-Star',
    "slug": 'va_fls',
    "state": 'Virginia',
  },
  {
    "city": 'Lynchburg',
    "country": 'USA',
    "name": 'The News & Advance',
    "slug": 'va_na',
    "state": 'Virginia',
  },
  {
    "city": 'McLean',
    "country": 'USA',
    "name": 'USA Today',
    "slug": 'usat',
    "state": 'Virginia',
  },
  {
    "city": 'Newport News',
    "country": 'USA',
    "name": 'Daily Press',
    "slug": 'va_dpress',
    "state": 'Virginia',
  },
  {
    "city": 'Norfolk',
    "country": 'USA',
    "name": 'The Virginian-Pilot',
    "slug": 'va_vp',
    "state": 'Virginia',
  },
  {
    "city": 'Petersburg',
    "country": 'USA',
    "name": 'The Progress-Index',
    "slug": 'va_tpi',
    "state": 'Virginia',
  },
  {
    "city": 'Richmond',
    "country": 'USA',
    "name": 'Richmond Times-Dispatch',
    "slug": 'va_rtd',
    "state": 'Virginia',
  },
  {
    "city": 'Roanoke',
    "country": 'USA',
    "name": 'The Roanoke Times',
    "slug": 'va_trt',
    "state": 'Virginia',
  },
  {
    "city": 'Staunton',
    "country": 'USA',
    "name": 'The News Leader',
    "slug": 'va_nl',
    "state": 'Virginia',
  },
  {
    "city": 'Waynesboro',
    "country": 'USA',
    "name": 'The News Virginian',
    "slug": 'va_nv',
    "state": 'Virginia',
  },
  {
    "city": 'Bremerton',
    "country": 'USA',
    "name": 'Kitsap Sun',
    "slug": 'wa_sun',
    "state": 'Washington',
  },
  {
    "city": 'Spokane',
    "country": 'USA',
    "name": 'The Spokesman-Review',
    "slug": 'wa_sr',
    "state": 'Washington',
  },
  {
    "city": 'Vancouver',
    "country": 'USA',
    "name": 'The Columbian',
    "slug": 'wa_col',
    "state": 'Washington',
  },
  {
    "city": 'Beckley',
    "country": 'USA',
    "name": 'The Register-Herald',
    "slug": 'wv_rh',
    "state": 'West Virginia',
  },
  {
    "city": 'Parkersburg',
    "country": 'USA',
    "name": 'Parkersburg News and Sentinel',
    "slug": 'wv_pns',
    "state": 'West Virginia',
  },
  {
    "city": 'Appleton',
    "country": 'USA',
    "name": 'The Post-Crescent',
    "slug": 'wi_pc',
    "state": 'Wisconsin',
  },
  {
    "city": 'Baraboo',
    "country": 'USA',
    "name": 'Baraboo News Republic',
    "slug": 'wi_bnr',
    "state": 'Wisconsin',
  },
  {
    "city": 'Beaver Dam',
    "country": 'USA',
    "name": 'Beaver Dam Daily Citizen',
    "slug": 'wi_bddc',
    "state": 'Wisconsin',
  },
  {
    "city": 'Chippewa Falls',
    "country": 'USA',
    "name": 'Chippewa Herald',
    "slug": 'wi_ch',
    "state": 'Wisconsin',
  },
  {
    "city": 'Fond du Lac',
    "country": 'USA',
    "name": 'The Reporter',
    "slug": 'wi_tr',
    "state": 'Wisconsin',
  },
  {
    "city": 'Green Bay',
    "country": 'USA',
    "name": 'Green Bay Press-Gazette',
    "slug": 'wi_gbp',
    "state": 'Wisconsin',
  },
  {
    "city": 'Janesville',
    "country": 'USA',
    "name": 'The Janesville Gazette',
    "slug": 'wi_jg',
    "state": 'Wisconsin',
  },
  {
    "city": 'Madison',
    "country": 'USA',
    "name": 'Wisconsin State Journal',
    "slug": 'wi_wsj',
    "state": 'Wisconsin',
  },
  {
    "city": 'Marshfield',
    "country": 'USA',
    "name": 'Marshfield News-Herald',
    "slug": 'wi_mnh',
    "state": 'Wisconsin',
  },
  {
    "city": 'Milwaukee',
    "country": 'USA',
    "name": 'Milwaukee Journal Sentinel',
    "slug": 'wi_mjs',
    "state": 'Wisconsin',
  },
  {
    "city": 'Oshkosh',
    "country": 'USA',
    "name": 'Oshkosh Northwestern',
    "slug": 'wi_on',
    "state": 'Wisconsin',
  },
  {
    "city": 'Portage',
    "country": 'USA',
    "name": 'Portage Daily Register',
    "slug": 'wi_pdr',
    "state": 'Wisconsin',
  },
  {
    "city": 'Sheboygan',
    "country": 'USA',
    "name": 'The Sheboygan Press',
    "slug": 'wi_sp',
    "state": 'Wisconsin',
  },
  {
    "city": 'Stevens Point',
    "country": 'USA',
    "name": 'Stevens Point Journal',
    "slug": 'wi_spj',
    "state": 'Wisconsin',
  },
  {
    "city": 'Wausau',
    "country": 'USA',
    "name": 'The Wausau Daily Herald',
    "slug": 'wi_wdh',
    "state": 'Wisconsin',
  },
  {
    "city": 'Wisconsin Rapids',
    "country": 'USA',
    "name": 'Daily Tribune',
    "slug": 'wi_dt',
    "state": 'Wisconsin',
  },
  {
    "city": 'Casper',
    "country": 'USA',
    "name": 'Casper Star-Tribune',
    "slug": 'wy_cst',
    "state": 'Wyoming',
  },
  {
    "city": 'Buenos Aires',
    "country": 'Argentina',
    "name": 'Clarín',
    "slug": 'arg_cla',
  },
  {
    "city": 'Posadas',
    "country": 'Argentina',
    "name": 'El Territorio',
    "slug": 'arg_et',
  },
  {
    "city": 'Perth',
    "country": 'Australia',
    "name": 'The West Australian',
    "slug": 'aus_wa',
  },
  {
    "city": 'Salzburg',
    "country": 'Austria',
    "name": 'Salzburger Nachrichten',
    "slug": 'aut_sn',
  },
  {
    "city": 'Vienna',
    "country": 'Austria',
    "name": 'Kurier',
    "slug": 'aut_kur',
  },
  {
    "city": 'Vienna',
    "country": 'Austria',
    "name": 'Der Standard',
    "slug": 'aut_ds',
  },
  {
    "city": 'Vorarlberg',
    "country": 'Austria',
    "name": 'Neue Vorarlberger Tageszeitung',
    "slug": 'aut_nvt',
  },
  {
    "city": 'Vorarlberg',
    "country": 'Austria',
    "name": 'Vorarlberger Nachrichten',
    "slug": 'aut_vn',
  },
  {
    "city": 'Brussels',
    "country": 'Belgium',
    "name": 'De Morgen',
    "slug": 'bel_dm',
  },
  {
    "city": 'Brasilia',
    "country": 'Brazil',
    "name": 'Correio Braziliense',
    "slug": 'bra_cb',
  },
  {
    "city": 'Itajaí',
    "country": 'Brazil',
    "name": 'DIARINHO',
    "slug": 'bra_diar',
  },
  {
    "city": 'Ponta Grossa',
    "country": 'Brazil',
    "name": 'Diário dos Campos',
    "slug": 'bra^pr_ddc',
  },
  {
    "city": 'Recife',
    "country": 'Brazil',
    "name": 'Jornal do Commercio',
    "slug": 'bra^pe_jdc',
  },
  {
    "city": 'Salvador da Bahia',
    "country": 'Brazil',
    "name": 'A Tarde',
    "slug": 'bra_atarde',
  },
  {
    "city": 'São Paulo',
    "country": 'Brazil',
    "name": 'O Estado de S. Paulo',
    "slug": 'bra_oe',
  },
  {
    "city": 'São Paulo',
    "country": 'Brazil',
    "name": 'Folha de S. Paulo',
    "slug": 'bra_fdsp',
  },
  {
    "city": 'Taubaté',
    "country": 'Brazil',
    "name": 'Diário de Taubaté',
    "slug": 'bra_dt',
  },
  {
    "city": 'Calgary',
    "country": 'Canada',
    "name": 'Calgary Herald',
    "slug": 'can_ch',
  },
  {
    "city": 'Calgary',
    "country": 'Canada',
    "name": 'The Calgary Sun',
    "slug": 'can_cs',
  },
  {
    "city": 'Edmonton',
    "country": 'Canada',
    "name": 'Edmonton Journal',
    "slug": 'can_ej',
  },
  {
    "city": 'Edmonton',
    "country": 'Canada',
    "name": 'Edmonton Sun',
    "slug": 'can_es',
  },
  {
    "city": 'Montreal',
    "country": 'Canada',
    "name": 'Montreal Gazette',
    "slug": 'can_mg',
  },
  {
    "city": 'Montreal',
    "country": 'Canada',
    "name": 'Le Journal de Montréal',
    "slug": 'can_jm',
  },
  {
    "city": 'Ottawa',
    "country": 'Canada',
    "name": 'The Ottawa Sun',
    "slug": 'can_os',
  },
  {
    "city": 'Toronto',
    "country": 'Canada',
    "name": 'The Globe and Mail',
    "slug": 'can_tgam',
  },
  {
    "city": 'Toronto',
    "country": 'Canada',
    "name": 'National Post',
    "slug": 'can_np',
  },
  {
    "city": 'Toronto',
    "country": 'Canada',
    "name": 'Toronto Star',
    "slug": 'can_ts',
  },
  {
    "city": 'Toronto',
    "country": 'Canada',
    "name": 'Toronto Sun',
    "slug": 'can_tsun',
  },
  {
    "city": 'Vancouver',
    "country": 'Canada',
    "name": 'The Vancouver Sun',
    "slug": 'can_vs',
  },
  {
    "city": 'Vancouver',
    "country": 'Canada',
    "name": 'The Province',
    "slug": 'can_tp',
  },
  {
    "city": 'Windsor',
    "country": 'Canada',
    "name": 'The Windsor Star',
    "slug": 'can_tws',
  },
  {
    "city": 'Winnipeg',
    "country": 'Canada',
    "name": 'Winnipeg Free Press',
    "slug": 'can_wfp',
  },
  {
    "city": 'Santiago',
    "country": 'Chile',
    "name": 'El Mercurio',
    "slug": 'chil_em',
  },
  {
    "city": 'Beijing',
    "country": 'China',
    "name": 'China Daily',
    "slug": 'chi_cd',
  },
  {
    "city": 'Beijing',
    "country": 'China',
    "name": 'People’s Daily',
    "slug": 'chi_pd',
  },
  {
    "city": 'Bucaramanga',
    "country": 'Colombia',
    "name": 'Vanguardia Liberal',
    "slug": 'col_vl',
  },
  {
    "city": 'Cartagena',
    "country": 'Colombia',
    "name": 'El Universal',
    "slug": 'col_eu',
  },
  {
    "city": 'Zagreb',
    "country": 'Croatia',
    "name": 'Vecernji List',
    "slug": 'cro_vl',
  },
  {
    "city": 'Nicosia',
    "country": 'Cyprus',
    "name": 'Phileleftheros',
    "slug": 'cyp_phil',
  },
  {
    "city": 'Copenhagen',
    "country": 'Denmark',
    "name": 'Politiken',
    "slug": 'den_pol',
  },
  {
    "city": 'Tallinn',
    "country": 'Estonia',
    "name": 'Õhtuleht',
    "slug": 'est_slo',
  },
  {
    "city": 'Suva',
    "country": 'Fiji',
    "name": 'The Fiji Times',
    "slug": 'fiji_ft',
  },
  {
    "city": 'Tbilisi',
    "country": 'Georgia',
    "name": 'The Messenger',
    "slug": 'geor_tm',
  },
  {
    "city": 'Bielefeld',
    "country": 'Germany',
    "name": 'Neue Westfälische',
    "slug": 'ger_nw',
  },
  {
    "city": 'Frankfurt',
    "country": 'Germany',
    "name": 'Frankfurter Allgemeine Zeitung',
    "slug": 'ger_faz',
  },
  {
    "city": 'Koblenz',
    "country": 'Germany',
    "name": 'Rhein-Zeitung',
    "slug": 'ger_rz',
  },
  {
    "city": 'Mannheim',
    "country": 'Germany',
    "name": 'Mannheimer Morgen',
    "slug": 'ger_mm',
  },
  {
    "city": 'Passau',
    "country": 'Germany',
    "name": 'Passauer Neue Presse',
    "slug": 'ger_pnp',
  },
  {
    "city": 'Athens',
    "country": 'Greece',
    "name": 'Kontra News',
    "slug": 'gree_kn',
  },
  {
    "city": 'Heraklion',
    "country": 'Greece',
    "name": 'Nea Kriti',
    "slug": 'gree_nk',
  },
  {
    "city": 'Volos',
    "country": 'Greece',
    "name": 'Taxydromos',
    "slug": 'gree_tax',
  },
  {
    "city": 'Chennai',
    "country": 'India',
    "name": 'New Indian Express',
    "slug": 'ind_nie',
  },
  {
    "city": 'Mumbai',
    "country": 'India',
    "name": 'Newsdanka',
    "slug": 'in_nsda',
  },
  {
    "city": 'Mumbai',
    "country": 'India',
    "name": 'Prahaar - Mumbai',
    "slug": 'ind_prahm',
  },
  {
    "city": 'Ratnagiri',
    "country": 'India',
    "name": 'Prahaar - Ratnagiri',
    "slug": 'ind_prahr',
  },
  {
    "city": 'Sindhudurg',
    "country": 'India',
    "name": 'Prahaar - Sindhudurg',
    "slug": 'ind_prahs',
  },
  {
    "city": 'Cork',
    "country": 'Ireland',
    "name": 'Irish Examiner',
    "slug": 'irl_ie',
  },
  {
    "city": 'Dublin',
    "country": 'Ireland',
    "name": 'Irish Times',
    "slug": 'irl_it',
  },
  {
    "city": 'Jerusalem',
    "country": 'Israel',
    "name": 'The Jerusalem Post',
    "slug": 'isr_jp',
  },
  {
    "city": 'RISHON LETZION',
    "country": 'Israel',
    "name": 'Yedioth Ahronoth',
    "slug": 'isr_ya',
  },
  {
    "city": 'Tel Aviv',
    "country": 'Israel',
    "name": 'Haaretz - English Edition',
    "slug": 'isr_ha',
  },
  {
    "city": 'Tel Aviv',
    "country": 'Israel',
    "name": 'Haaretz - Hebrew Edition',
    "slug": 'isr_hahe',
  },
  {
    "city": 'Torino',
    "country": 'Italy',
    "name": 'La Stampa',
    "slug": 'ita_ls',
  },
  {
    "city": 'Kuwait',
    "country": 'Kuwait',
    "name": 'Kuwait Times',
    "slug": 'kuw_kt',
  },
  {
    "city": 'Luxembourg City',
    "country": 'Luxembourg',
    "name": 'Luxemburger Wort',
    "slug": 'lux_lw',
  },
  {
    "city": 'Kuala Lumpur',
    "country": 'Malaysia',
    "name": 'Star',
    "slug": 'mal_star',
  },
  {
    "city": 'Guadalajara',
    "country": 'Mexico',
    "name": 'El Informador',
    "slug": 'mex_inf',
  },
  {
    "city": 'Guadalajara',
    "country": 'Mexico',
    "name": 'Milenio Jalisco',
    "slug": 'mex_pm',
  },
  {
    "city": 'León',
    "country": 'Mexico',
    "name": 'Milenio León',
    "slug": 'mex_ml',
  },
  {
    "city": 'Mérida',
    "country": 'Mexico',
    "name": 'Diario de Yucatán',
    "slug": 'mex_ddy',
  },
  {
    "city": 'Mexico City',
    "country": 'Mexico',
    "name": 'La Razón de México',
    "slug": 'mex_lrdm',
  },
  {
    "city": 'Mexico City',
    "country": 'Mexico',
    "name": 'El Universal',
    "slug": 'mex_eu',
  },
  {
    "city": 'Mexico City',
    "country": 'Mexico',
    "name": 'Reforma',
    "slug": 'mex_ref',
  },
  {
    "city": 'Monterrey',
    "country": 'Mexico',
    "name": 'Milenio Monterrey',
    "slug": 'mex_mddm',
  },
  {
    "city": 'Pachuca',
    "country": 'Mexico',
    "name": 'Milenio Hidalgo',
    "slug": 'mex_mh',
  },
  {
    "city": 'Saltillo',
    "country": 'Mexico',
    "name": 'Vanguardia',
    "slug": 'mex_van',
  },
  {
    "city": 'Tampico',
    "country": 'Mexico',
    "name": 'Milenio Tamaulipas',
    "slug": 'mex_mt',
  },
  {
    "city": 'Toluca',
    "country": 'Mexico',
    "name": 'Milenio Estado de México',
    "slug": 'mex_medm',
  },
  {
    "city": 'Torreon',
    "country": 'Mexico',
    "name": 'Milenio Laguna',
    "slug": 'mex_lom',
  },
  {
    "city": 'Amsterdam',
    "country": 'Netherlands',
    "name": 'Het Parool',
    "slug": 'net_hp',
  },
  {
    "city": 'Amsterdam',
    "country": 'Netherlands',
    "name": 'Trouw',
    "slug": 'net_trouw',
  },
  {
    "city": 'Amsterdam',
    "country": 'Netherlands',
    "name": 'Het Financieele Dagblad',
    "slug": 'net_hfd',
  },
  {
    "city": 'Amsterdam',
    "country": 'Netherlands',
    "name": 'de Volkskrant',
    "slug": 'net_dv',
  },
  {
    "city": 'Rotterdam',
    "country": 'Netherlands',
    "name": 'AD',
    "slug": 'net_ad2',
  },
  {
    "city": 'Christchurch',
    "country": 'New Zealand',
    "name": 'The Press',
    "slug": 'newz_tp',
  },
  {
    "city": 'Wellington',
    "country": 'New Zealand',
    "name": 'The Dominion Post',
    "slug": 'newz_dp',
  },
  {
    "city": 'Karachi',
    "country": 'Pakistan',
    "name": 'Dawn',
    "slug": 'pak_dawn',
  },
  {
    "city": 'Panama City',
    "country": 'Panama',
    "name": 'La Estrella de Panama',
    "slug": 'pan_lep',
  },
  {
    "city": 'Manila',
    "country": 'Philippines',
    "name": 'Manila Bulletin',
    "slug": 'phi_mb',
  },
  {
    "city": 'Bratislava',
    "country": 'Slovakia',
    "name": 'Denník N',
    "slug": 'slk_den',
  },
  {
    "city": 'Cape Town',
    "country": 'South Africa',
    "name": 'Cape Times',
    "slug": 'saf_ct',
  },
  {
    "city": 'Durban',
    "country": 'South Africa',
    "name": 'The Mercury',
    "slug": 'saf_tm',
  },
  {
    "city": 'Seoul',
    "country": 'South Korea',
    "name": 'The Dong-a Ilbo',
    "slug": 'skor_did',
  },
  {
    "city": 'Seoul',
    "country": 'South Korea',
    "name": 'JoongAng Ilbo',
    "slug": 'skor_jai',
  },
  {
    "city": 'Seoul',
    "country": 'South Korea',
    "name": 'The Chosun Ilbo',
    "slug": 'skor_ci',
  },
  {
    "city": 'Seoul',
    "country": 'South Korea',
    "name": 'The Maeil Business Newspaper',
    "slug": 'skor_mb',
  },
  {
    "city": 'Barcelona',
    "country": 'Spain',
    "name": 'ARA',
    "slug": 'spa_ara',
  },
  {
    "city": 'Barcelona',
    "country": 'Spain',
    "name": 'La Vanguardia',
    "slug": 'spa_lv',
  },
  {
    "city": 'Lleida',
    "country": 'Spain',
    "name": 'Segre',
    "slug": 'spa_segre',
  },
  {
    "city": 'Göteborg',
    "country": 'Sweden',
    "name": 'Göteborgstidningen',
    "slug": 'swe_gt',
  },
  {
    "city": 'Malmö',
    "country": 'Sweden',
    "name": 'Kvällsposten',
    "slug": 'swe_kv',
  },
  {
    "city": 'Stockholm',
    "country": 'Sweden',
    "name": 'Dagens Nyheter',
    "slug": 'swe_dn',
  },
  {
    "city": 'Stockholm',
    "country": 'Sweden',
    "name": 'Expressen',
    "slug": 'swe_ex',
  },
  {
    "city": 'Zürich',
    "country": 'Switzerland',
    "name": 'Blick',
    "slug": 'swi_bk',
  },
  {
    "city": 'Taipei',
    "country": 'Taiwan',
    "name": 'The Merit Times',
    "slug": 'taiw_tmt',
  },
  {
    "city": 'Singapore',
    "country": 'The Republic of Singapore',
    "name": 'Lianhe Zaobao',
    "slug": 'sing_lz',
  },
  {
    "city": 'Istanbul',
    "country": 'Turkey',
    "name": 'Fotomac',
    "slug": 'tur_foto',
  },
  {
    "city": 'Istanbul',
    "country": 'Turkey',
    "name": 'Takvim',
    "slug": 'tur_tak',
  },
  {
    "city": 'Istanbul',
    "country": 'Turkey',
    "name": 'Daily Sabah',
    "slug": 'tur_ds',
  },
  {
    "city": 'Istanbul',
    "country": 'Turkey',
    "name": 'Sabah',
    "slug": 'tur_sab',
  },
  {
    "city": 'Izmir',
    "country": 'Turkey',
    "name": 'Ticaret Gazetesi',
    "slug": 'tur_ticar',
  },
  {
    "city": 'Izmir',
    "country": 'Turkey',
    "name": 'Yeniasir',
    "slug": 'tur_yen',
  },
  {
    "city": 'Abu Dhabi',
    "country": 'United Arab Emirates',
    "name": 'The National',
    "slug": 'uae_tn',
  },
  {
    "city": 'Dubai',
    "country": 'United Arab Emirates',
    "name": 'Gulf News',
    "slug": 'uae_gn',
  },
  {
    "city": 'Centre',
    "country": 'USA',
    "name": 'The Cherokee County Herald',
    "slug": 'al_cch',
    "state": 'Alabama',
  },
  {
    "city": 'Chino Valley',
    "country": 'USA',
    "name": 'Chino Valley Review',
    "slug": 'az_cvr',
    "state": 'Arizona',
  },
  {
    "city": 'Prescott Valley',
    "country": 'USA',
    "name": 'Prescott Valley Tribune',
    "slug": 'az_pvt',
    "state": 'Arizona',
  },
  {
    "city": 'Conway',
    "country": 'USA',
    "name": 'Log Cabin Democrat',
    "slug": 'ar_lcd',
    "state": 'Arkansas',
  },
  {
    "city": 'Fresno',
    "country": 'USA',
    "name": 'The Fresno Bee',
    "slug": 'ca_fb',
    "state": 'California',
  },
  {
    "city": 'Merced',
    "country": 'USA',
    "name": 'Merced Sun-Star',
    "slug": 'ca_mss',
    "state": 'California',
  },
  {
    "city": 'Modesto',
    "country": 'USA',
    "name": 'The Modesto Bee',
    "slug": 'ca_mb',
    "state": 'California',
  },
  {
    "city": 'Salinas',
    "country": 'USA',
    "name": 'The Salinas Californian',
    "slug": 'ca_sc',
    "state": 'California',
  },
  {
    "city": 'San Luis Obispo',
    "country": 'USA',
    "name": 'The Tribune',
    "slug": 'ca_tt',
    "state": 'California',
  },
  {
    "city": 'Tiburon',
    "country": 'USA',
    "name": 'The Ark',
    "slug": 'ca_ark',
    "state": 'California',
  },
  {
    "city": 'Durango',
    "country": 'USA',
    "name": 'The Durango Herald',
    "slug": 'co_dh',
    "state": 'Colorado',
  },
  {
    "city": 'Washington',
    "country": 'USA',
    "name": 'The Hill',
    "slug": 'dc_hill',
    "state": 'District of Columbia',
  },
  {
    "city": 'Bradenton',
    "country": 'USA',
    "name": 'The Bradenton Herald',
    "slug": 'fl_bh',
    "state": 'Florida',
  },
  {
    "city": 'Key West',
    "country": 'USA',
    "name": 'Keys Citizen',
    "slug": 'fl_kc',
    "state": 'Florida',
  },
  {
    "city": 'St. Petersburg',
    "country": 'USA',
    "name": 'TBT*',
    "slug": 'fl_tb',
    "state": 'Florida',
  },
  {
    "city": 'Columbus',
    "country": 'USA',
    "name": 'Ledger-Enquirer',
    "slug": 'ga_le',
    "state": 'Georgia',
  },
  {
    "city": 'Macon',
    "country": 'USA',
    "name": 'The Telegraph',
    "slug": 'ga_tt',
    "state": 'Georgia',
  },
  {
    "city": 'Boise',
    "country": 'USA',
    "name": 'Idaho Statesman',
    "slug": 'id_is',
    "state": 'Idaho',
  },
  {
    "city": 'Coeur d’Alene',
    "country": 'USA',
    "name": 'Coeur d’Alene Press',
    "slug": 'id_cdap',
    "state": 'Idaho',
  },
  {
    "city": 'Sandpoint',
    "country": 'USA',
    "name": 'Bonner County Daily Bee',
    "slug": 'id_bcdb',
    "state": 'Idaho',
  },
  {
    "city": 'Belleville',
    "country": 'USA',
    "name": 'Belleville News-Democrat',
    "slug": 'il_bnd',
    "state": 'Illinois',
  },
  {
    "city": 'Elgin',
    "country": 'USA',
    "name": 'The Courier-News',
    "slug": 'il_cn',
    "state": 'Illinois',
  },
  {
    "city": 'Naperville',
    "country": 'USA',
    "name": 'The Naperville Sun',
    "slug": 'il_ns',
    "state": 'Illinois',
  },
  {
    "city": 'Frankfort',
    "country": 'USA',
    "name": 'Frankfort Times',
    "slug": 'in_ft',
    "state": 'Indiana',
  },
  {
    "city": 'New Castle',
    "country": 'USA',
    "name": 'The Courier-Times',
    "slug": 'in_tct',
    "state": 'Indiana',
  },
  {
    "city": 'Peru',
    "country": 'USA',
    "name": 'Plain Dealer',
    "slug": 'in_pd',
    "state": 'Indiana',
  },
  {
    "city": 'West Branch',
    "country": 'USA',
    "name": 'West Branch Times',
    "slug": 'ia_wbt',
    "state": 'Iowa',
  },
  {
    "city": 'Wichita',
    "country": 'USA',
    "name": 'The Wichita Eagle',
    "slug": 'ks_we',
    "state": 'Kansas',
  },
  {
    "city": 'Bowling Green',
    "country": 'USA',
    "name": 'Daily News',
    "slug": 'ky_dn',
    "state": 'Kentucky',
  },
  {
    "city": 'Lexington',
    "country": 'USA',
    "name": 'Lexington Herald-Leader',
    "slug": 'ky_lhl',
    "state": 'Kentucky',
  },
  {
    "city": 'Alexandria',
    "country": 'USA',
    "name": 'The Town Talk',
    "slug": 'la_ttt',
    "state": 'Louisiana',
  },
  {
    "city": 'Opelousas',
    "country": 'USA',
    "name": 'Daily World',
    "slug": 'la_dw',
    "state": 'Louisiana',
  },
  {
    "city": 'Biloxi',
    "country": 'USA',
    "name": 'Sun Herald',
    "slug": 'ms_sh',
    "state": 'Mississippi',
  },
  {
    "city": 'Greenwood',
    "country": 'USA',
    "name": 'Greenwood Commonwealth',
    "slug": 'ms_gc',
    "state": 'Mississippi',
  },
  {
    "city": 'Hattiesburg',
    "country": 'USA',
    "name": 'Hattiesburg American',
    "slug": 'ms_ha',
    "state": 'Mississippi',
  },
  {
    "city": 'Wiggins',
    "country": 'USA',
    "name": 'Stone County Enterprise',
    "slug": 'ms_sce',
    "state": 'Mississippi',
  },
  {
    "city": 'Columbia Falls',
    "country": 'USA',
    "name": 'Hungry Horse News',
    "slug": 'mt_hhn',
    "state": 'Montana',
  },
  {
    "city": 'Kalispell',
    "country": 'USA',
    "name": 'Bigfork Eagle',
    "slug": 'mt_be',
    "state": 'Montana',
  },
  {
    "city": 'Plains',
    "country": 'USA',
    "name": 'Mineral Independent',
    "slug": 'mt_mi',
    "state": 'Montana',
  },
  {
    "city": 'Plains',
    "country": 'USA',
    "name": 'Valley Press',
    "slug": 'mt_vp',
    "state": 'Montana',
  },
  {
    "city": 'Polson',
    "country": 'USA',
    "name": 'Lake County Leader',
    "slug": 'mt_lcl',
    "state": 'Montana',
  },
  {
    "city": 'Whitefish',
    "country": 'USA',
    "name": 'Whitefish Pilot',
    "slug": 'mt_wp',
    "state": 'Montana',
  },
  {
    "city": 'Farmington',
    "country": 'USA',
    "name": 'The Tri-City Record',
    "slug": 'nm_tcr',
    "state": 'New Mexico',
  },
  {
    "city": 'Lima',
    "country": 'USA',
    "name": 'The Lima News',
    "slug": 'oh_ln',
    "state": 'Ohio',
  },
  {
    "city": 'Portland',
    "country": 'USA',
    "name": 'The Oregonian',
    "slug": 'or_to',
    "state": 'Oregon',
  },
  {
    "city": 'Johnstown',
    "country": 'USA',
    "name": 'The Tribune-Democrat',
    "slug": 'pa_td',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Lancaster',
    "country": 'USA',
    "name": 'LNP',
    "slug": 'pa_lnp',
    "state": 'Pennsylvania',
  },
  {
    "city": 'State College',
    "country": 'USA',
    "name": 'Centre Daily Times',
    "slug": 'pa_cdt',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Bluffton',
    "country": 'USA',
    "name": 'The Island Packet',
    "slug": 'sc_ip',
    "state": 'South Carolina',
  },
  {
    "city": 'Carthage',
    "country": 'USA',
    "name": 'The Panola Watchman',
    "slug": 'tx_pw',
    "state": 'Texas',
  },
  {
    "city": 'Galveston',
    "country": 'USA',
    "name": 'Galveston County Daily News',
    "slug": 'tx_gcdn',
    "state": 'Texas',
  },
  {
    "city": 'Henderson',
    "country": 'USA',
    "name": 'The Henderson News',
    "slug": 'tx_thn',
    "state": 'Texas',
  },
  {
    "city": 'Kilgore',
    "country": 'USA',
    "name": 'Kilgore News Herald',
    "slug": 'tx_knh',
    "state": 'Texas',
  },
  {
    "city": 'Lufkin',
    "country": 'USA',
    "name": 'The Lufkin Daily News',
    "slug": 'tx_ldn',
    "state": 'Texas',
  },
  {
    "city": 'Bellingham',
    "country": 'USA',
    "name": 'Bellingham Herald',
    "slug": 'wa_bh',
    "state": 'Washington',
  },
  {
    "city": 'Kennewick',
    "country": 'USA',
    "name": 'Tri-City Herald',
    "slug": 'wa_tch',
    "state": 'Washington',
  },
  {
    "city": 'Moses Lake',
    "country": 'USA',
    "name": 'Columbia Basin Herald',
    "slug": 'wa_cbh',
    "state": 'Washington',
  },
  {
    "city": 'Olympia',
    "country": 'USA',
    "name": 'The Olympian',
    "slug": 'wa_to',
    "state": 'Washington',
  },
  {
    "city": 'Seattle',
    "country": 'USA',
    "name": 'The Seattle Times',
    "slug": 'wa_st',
    "state": 'Washington',
  },
  {
    "city": 'Tacoma',
    "country": 'USA',
    "name": 'The News Tribune',
    "slug": 'wa_nt',
    "state": 'Washington',
  },
  {
    "city": 'Fairmont',
    "country": 'USA',
    "name": 'Times West Virginian',
    "slug": 'wv_twv',
    "state": 'West Virginia',
  },
  {
    "city": 'Menomonie',
    "country": 'USA',
    "name": 'Dunn County News',
    "slug": 'wi_dcn',
    "state": 'Wisconsin',
  },
  {
    "city": 'Fort Macleod',
    "country": 'Canada',
    "name": 'The Macleod Gazette',
    "slug": 'can_tmg',
  },
  {
    "city": 'Saltillo',
    "country": 'Mexico',
    "name": 'El Heraldo de Saltillo',
    "slug": 'mex_ehds',
  },
  {
    "city": 'Casablanca',
    "country": 'Morocco',
    "name": 'Alahdath Almaghrebia',
    "slug": 'mor_aa',
  },
  {
    "city": 'Moscow',
    "country": 'Russia',
    "name": 'Moskovskaya Pravda',
    "slug": 'rus_mp',
  },
  {
    "city": 'Moscow',
    "country": 'USA',
    "name": 'Moscow-Pullman Daily News',
    "slug": 'id_mpdn',
    "state": 'Idaho',
  },
  {
    "city": 'Easton',
    "country": 'USA',
    "name": 'The Express-Times',
    "slug": 'pa_et',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Sharon',
    "country": 'USA',
    "name": 'The Herald',
    "slug": 'pa_her',
    "state": 'Pennsylvania',
  },
  {
    "city": 'Prishtina',
    "country": 'Kosovo',
    "name": 'Koha Ditore',
    "slug": 'kos_kd',
  },
  {
    "city": 'Durban',
    "country": 'South Africa',
    "name": 'The Independent',
    "slug": 'saf_ti',
  },
  {
    "city": 'Mattoon',
    "country": 'USA',
    "name": 'Journal Gazette',
    "slug": 'il_jg',
    "state": 'Illinois',
  },
  {
    "city": 'Doha',
    "country": 'Qatar',
    "name": 'The Peninsula',
    "slug": 'qatar_ts',
  },
  {
    "city": 'Berlin',
    "country": 'Germany',
    "name": 'Die Tageszeitung',
    "slug": 'ger_taz',
  },
  {
    "city": 'Osburn',
    "country": 'USA',
    "name": 'Shoshone News-Press',
    "slug": 'id_snp',
    "state": 'Idaho',
  },
  {
    "city": 'Albuquerque',
    "country": 'USA',
    "name": 'Albuquerque Journal',
    "slug": 'nm_aj',
    "state": 'New Mexico',
  },
  {
    "city": 'Washington',
    "country": 'USA',
    "name": 'The Washington Informer',
    "slug": 'dc_wi',
    "state": 'District of Columbia',
  },
  {
    "city": 'Bonners Ferry',
    "country": 'USA',
    "name": 'Bonners Ferry Herald',
    "slug": 'id_bfh',
    "state": 'Idaho',
  },
  {
    "city": 'Hinsdale',
    "country": 'USA',
    "name": 'The Hinsdalean',
    "slug": 'il_th',
    "state": 'Illinois',
  },
  {
    "city": 'Belton',
    "country": 'USA',
    "name": 'North Cass Herald',
    "slug": 'mo_nch',
    "state": 'Missouri',
  },
  {
    "city": 'Beachwood',
    "country": 'USA',
    "name": 'Columbus Jewish News',
    "slug": 'oh_cojn',
    "state": 'Ohio',
  },
  {
    "city": 'Dallas',
    "country": 'USA',
    "name": 'Dallas Voice',
    "slug": 'tx_dv',
    "state": 'Texas',
  },
  {
    "city": 'Arlington',
    "country": 'USA',
    "name": 'Arlington Catholic Herald',
    "slug": 'va_ach',
    "state": 'Virginia',
  },
  {
    "city": 'Medford',
    "country": 'USA',
    "name": 'The Star News',
    "slug": 'wi_sn',
    "state": 'Wisconsin',
  },
  {
    "city": 'Satu Mare',
    "country": 'Romania',
    "name": 'Informatia Zilei',
    "slug": 'rom_iz',
  },
  {
    "city": 'Batesville',
    "country": 'USA',
    "name": 'Batesville Daily Guard',
    "slug": 'ar_bdg',
    "state": 'Arkansas',
  },
  {
    "city": 'Searcy',
    "country": 'USA',
    "name": 'The Daily Citizen',
    "slug": 'ar_dc',
    "state": 'Arkansas',
  },
  {
    "city": 'Oakland',
    "country": 'USA',
    "name": 'Oakland Tribune',
    "slug": 'ca_ot',
    "state": 'California',
  },
  {
    "city": 'Palo Alto',
    "country": 'USA',
    "name": 'The Daily News',
    "slug": 'ca_tdn',
    "state": 'California',
  },
  {
    "city": 'Torrington',
    "country": 'USA',
    "name": 'The Register Citizen',
    "slug": 'ct_rc',
    "state": 'Connecticut',
  },
  {
    "city": 'Beachwood',
    "country": 'USA',
    "name": 'Cleveland Jewish News',
    "slug": 'oh_cjn',
    "state": 'Ohio',
  },
  {
    "city": 'Vilnius',
    "country": 'Lithuania',
    "name": 'Lietuvos Rytas',
    "slug": 'lith_lr',
  },
  {
    "city": 'New Delhi',
    "country": 'India',
    "name": 'The Sunday Standard',
    "slug": 'ind_ss',
  },
]
